### ISSUE TITLE
Exercise 4/8 "Good Old Form" does not run verification

### ISSUE THREAD

**Issue by Orbyt** [azat-co/expressworks#121]
The Good Old Form exercise has you take input and reverse the input, printing it to the console. My app successfully prints the reversed string, but then does nothing, and the verification does not run.

I've tried killing all node processes and re-running, this seems to have no effect.

After a minute or two, the following is thrown and the app terminates:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:200:15)
    at Socket.socketOnEnd (_http_client.js:292:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by Orbyt** [comment]
Ah, I was simply logging the provided result, the solution uses `res.send()`, which works, so closing.
