### ISSUE TITLE
"Cannot find module 'express'"

### ISSUE THREAD

**Issue by ericlathrop** [azat-co/expressworks#35]
Trying to run the Hello World exercise on Linux:
```
eric@nas:~/expressworks$ expressworks run program.js
Running "HELLO WORLD!"...


module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/eric/expressworks/program.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```
My program.js looks like:
```
var express = require("express");
var app = express();
app.get("/", function(req, res) {
	res.end("Hello World");
});
app.listen(process.argv[2]);
```

**Comment by Rockstar79** [comment]
I made the same assumption that `npm install express` would install all dependencies as other tutorials I've followed on Node School have. This should be mentioned in a more detailed task description. It may be an obvious step when building a project from scratch but within the context of a tutorial I would expect it to be mentioned if the install process doesn't give the user everything out of the box.

I managed to complete the task after following the install instructions from the [Express js website](http://expressjs.com/starter/installing.html) and running the verify command again.
